"use client";
import{useEffect,useState}from"react";
import{Archive,CalendarDays,Plus,Target}from"lucide-react";
import{Button}from"@/components/ui/button";
import{Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle}from"@/components/ui/dialog";
import{MoneyInput}from"@/components/ui/money-input";
import{EmptyState}from"@/components/ui/empty-state";
import{loadState,saveState}from"@/lib/storage/store";
import{formatINR}from"@/lib/domain/money";
import{goalProgress}from"@/lib/domain/planning";
import{formatShortDate}from"@/lib/domain/date";
import type{FinanceState,GoalItem,RecurringItem}from"@/types/finance";

export function GoalsManager(){
 const[s,setS]=useState<FinanceState|null>(null),[addOpen,setAddOpen]=useState(false),[contribute,setContribute]=useState<GoalItem|null>(null);
 useEffect(()=>setS(loadState()),[]);
 if(!s)return <div className="surface" aria-busy="true">Loading goals…</div>;
 const goals=s.goals||[],active=goals.filter(g=>g.status==="active"),target=active.reduce((n,g)=>n+g.targetMinor,0),saved=active.reduce((n,g)=>n+g.savedMinor,0),commit=(n:FinanceState)=>{setS(n);saveState(n)};
 return <>
  <div className="goalSummary"><div><span>Saved toward goals</span><strong>{formatINR(saved)}</strong><small>Across {active.length} active goals</small></div><div><span>Total target</span><strong>{formatINR(target)}</strong><small>{target?Math.round(saved/target*100):0}% funded overall</small></div><Button onClick={()=>setAddOpen(true)}><Plus size={16}/> Add goal</Button></div>
  <div className="surface goalSurface"><div className="surfaceHead"><div><span className="sectionKicker">ACTIVE GOALS</span><h2>Progress you can see</h2></div></div>{active.length?<div className="goalCards">{active.map(g=>{const pct=goalProgress(g.savedMinor,g.targetMinor);return <article className="goalCard" key={g.id}><div className="goalCardIcon"><Target size={20}/></div><div className="goalCardBody"><div className="goalCardHead"><div><h3>{g.name}</h3><span>{formatINR(g.savedMinor)} of {formatINR(g.targetMinor)}</span></div><strong>{pct}%</strong></div><div className="goalTrack"><i style={{width:pct+"%"}}/></div><div className="goalCardFoot"><span>{g.targetDate?"Target "+formatShortDate(g.targetDate):"No target date"}</span><Button size="sm" variant="secondary" onClick={()=>setContribute(g)}>Add contribution</Button></div></div></article>})}</div>:<EmptyState title="No active goals" body="Create a goal when you have something specific to save toward." action={<Button onClick={()=>setAddOpen(true)}><Plus size={15}/> Add goal</Button>}/>}</div>
  <AddGoalDialog open={addOpen} onOpenChange={setAddOpen} onSave={g=>{commit({...s,goals:[...goals,g]});setAddOpen(false)}}/>
  <ContributionDialog goal={contribute} open={!!contribute} onOpenChange={v=>{if(!v)setContribute(null)}} onSave={amount=>{if(!contribute)return;commit({...s,goals:goals.map(x=>x.id===contribute.id?{...x,savedMinor:Math.min(x.targetMinor,x.savedMinor+amount),status:x.savedMinor+amount>=x.targetMinor?"completed":"active"}:x)});setContribute(null)}}/>
 </>;
}

function AddGoalDialog({open,onOpenChange,onSave}:{open:boolean;onOpenChange:(v:boolean)=>void;onSave:(g:GoalItem)=>void}){const[name,setName]=useState(""),[target,setTarget]=useState(""),[date,setDate]=useState("");useEffect(()=>{if(open){setName("");setTarget("");setDate("")}},[open]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><form onSubmit={e=>{e.preventDefault();const amount=Math.round(Number(target)*100);if(!name.trim()||amount<=0)return;onSave({id:crypto.randomUUID(),name:name.trim(),targetMinor:amount,savedMinor:0,targetDate:date||undefined,status:"active"})}}><DialogHeader><DialogTitle>Add savings goal</DialogTitle><DialogDescription>Track a target without turning it into another obligation.</DialogDescription></DialogHeader><div className="dialogFields"><label className="span2"><span>Goal name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Emergency fund"/></label><label><span>Target amount</span><MoneyInput value={target} onChange={e=>setTarget(e.target.value)} placeholder="500000"/></label><label><span>Target date <small>optional</small></span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><DialogFooter><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit">Add goal</Button></DialogFooter></form></DialogContent></Dialog>}

function ContributionDialog({goal,open,onOpenChange,onSave}:{goal:GoalItem|null;open:boolean;onOpenChange:(v:boolean)=>void;onSave:(amount:number)=>void}){const[value,setValue]=useState("");useEffect(()=>{if(open)setValue("")},[open]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add contribution</DialogTitle><DialogDescription>{goal?goal.name:"Goal"} · This demo treats contributions as earmarked progress; it does not move cash between accounts.</DialogDescription></DialogHeader><label className="dialogLabel"><span>Contribution</span><MoneyInput value={value} onChange={e=>setValue(e.target.value)} placeholder="10000"/></label><DialogFooter><Button variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>{const n=Math.round(Number(value)*100);if(n>0)onSave(n)}}>Add contribution</Button></DialogFooter></DialogContent></Dialog>}

export function RecurringManager(){
 const[s,setS]=useState<FinanceState|null>(null),[open,setOpen]=useState(false);
 useEffect(()=>setS(loadState()),[]);
 if(!s)return <div className="surface" aria-busy="true">Loading commitments…</div>;
 const items=s.recurring||[],active=items.filter(x=>x.active),commit=(n:FinanceState)=>{setS(n);saveState(n)};
 return <div className="surface recurringSurface"><div className="surfaceHead"><div><span className="sectionKicker">UPCOMING COMMITMENTS</span><h2>Bills & subscriptions</h2></div><Button variant="secondary" size="sm" onClick={()=>setOpen(true)}><Plus size={15}/> Add recurring</Button></div>{active.length?<div className="recurringList">{active.slice().sort((a,b)=>a.dueDay-b.dueDay).map(x=><div className="recurringRow" key={x.id}><div className="recurringIcon"><CalendarDays size={18}/></div><div><b>{x.name}</b><span>{x.kind==="subscription"?"Subscription":"Bill"} · due day {x.dueDay}</span></div><strong>{formatINR(x.amountMinor)}</strong><button aria-label={"Archive "+x.name} onClick={()=>commit({...s,recurring:items.map(y=>y.id===x.id?{...y,active:false}:y)})}><Archive size={15}/></button></div>)}</div>:<EmptyState title="No recurring commitments" body="Add bills or subscriptions to keep upcoming outflows visible."/>}<AddRecurringDialog open={open} onOpenChange={setOpen} onSave={item=>{commit({...s,recurring:[...items,item]});setOpen(false)}}/></div>;
}

function AddRecurringDialog({open,onOpenChange,onSave}:{open:boolean;onOpenChange:(v:boolean)=>void;onSave:(i:RecurringItem)=>void}){const[name,setName]=useState(""),[amount,setAmount]=useState(""),[dueDay,setDueDay]=useState("1"),[kind,setKind]=useState<"bill"|"subscription">("bill");useEffect(()=>{if(open){setName("");setAmount("");setDueDay("1");setKind("bill")}},[open]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><form onSubmit={e=>{e.preventDefault();const value=Math.round(Number(amount)*100),day=Math.max(1,Math.min(31,Number(dueDay)||1));if(!name.trim()||value<=0)return;onSave({id:crypto.randomUUID(),name:name.trim(),kind,amountMinor:value,dueDay:day,active:true})}}><DialogHeader><DialogTitle>Add recurring commitment</DialogTitle><DialogDescription>Keep regular bills and subscriptions visible before they are due.</DialogDescription></DialogHeader><div className="dialogFields"><label className="span2"><span>Name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Electricity"/></label><label><span>Type</span><select value={kind} onChange={e=>setKind(e.target.value as "bill"|"subscription")}><option value="bill">Bill</option><option value="subscription">Subscription</option></select></label><label><span>Due day</span><input type="number" min="1" max="31" value={dueDay} onChange={e=>setDueDay(e.target.value)}/></label><label className="span2"><span>Amount</span><MoneyInput value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label></div><DialogFooter><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit">Add commitment</Button></DialogFooter></form></DialogContent></Dialog>}