"use client";
import{useEffect,useMemo,useState}from"react";
import{Pencil,Plus}from"lucide-react";
import{Button}from"@/components/ui/button";
import{Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle}from"@/components/ui/dialog";
import{MoneyInput}from"@/components/ui/money-input";
import{EmptyState}from"@/components/ui/empty-state";
import{AllocationChart}from"@/components/charts/allocation-chart";
import{loadState,saveState}from"@/lib/storage/store";
import{formatINR}from"@/lib/domain/money";
import{portfolioCost,portfolioGain,portfolioValue}from"@/lib/domain/portfolio";
import{formatShortDate,localDateKey}from"@/lib/domain/date";
import type{FinanceState,Holding}from"@/types/finance";

export function PortfolioManager(){
 const[s,setS]=useState<FinanceState|null>(null),[addOpen,setAddOpen]=useState(false),[edit,setEdit]=useState<Holding|null>(null);
 useEffect(()=>setS(loadState()),[]);
 const allocation=useMemo(()=>{if(!s)return[];const map=new Map<string,number>();for(const h of s.holdings||[])map.set(h.assetClass,(map.get(h.assetClass)||0)+h.valueMinor);return[...map].map(([name,value])=>({name,value}))},[s]);
 if(!s)return <div className="surface" aria-busy="true">Loading investments…</div>;
 const h=s.holdings||[],value=portfolioValue(h),cost=portfolioCost(h),gain=portfolioGain(h),gainPct=cost?Math.round(gain/cost*1000)/10:0,commit=(n:FinanceState)=>{setS(n);saveState(n)};
 return <>
  <div className="portfolioSummary"><div><span>Portfolio value</span><strong>{formatINR(value)}</strong><small>{h.length} holdings tracked</small></div><div><span>Amount invested</span><strong>{formatINR(cost)}</strong><small>Recorded cost basis</small></div><div><span>Gain / loss</span><strong className={gain>=0?"positiveText":"negativeText"}>{gain>=0?"+":""}{formatINR(gain)}</strong><small>{gain>=0?"+":""}{gainPct}%</small></div><Button onClick={()=>setAddOpen(true)}><Plus size={16}/> Add holding</Button></div>
  <div className="investmentGrid">
   <div className="surface holdingsSurface"><div className="surfaceHead"><div><span className="sectionKicker">HOLDINGS</span><h2>What you own</h2></div></div>{h.length?<><table className="dataTable desktopOnly"><thead><tr><th>Holding</th><th>Asset class</th><th>Cost</th><th>Current value</th><th>Gain/loss</th><th aria-label="Actions"/></tr></thead><tbody>{h.map(x=>{const g=x.valueMinor-x.costMinor;return <tr key={x.id}><td><b>{x.name}</b><small className="cellSub">Updated {formatShortDate(x.valuedAt)}</small></td><td>{x.assetClass}</td><td>{formatINR(x.costMinor)}</td><td>{formatINR(x.valueMinor)}</td><td className={g>=0?"positiveText":"negativeText"}>{g>=0?"+":""}{formatINR(g)}</td><td><button className="tableIcon" aria-label={"Update "+x.name} onClick={()=>setEdit(x)}><Pencil size={15}/></button></td></tr>})}</tbody></table><div className="holdingCards mobileOnly">{h.map(x=>{const g=x.valueMinor-x.costMinor;return <button key={x.id} onClick={()=>setEdit(x)}><span><b>{x.name}</b><small>{x.assetClass} · {formatShortDate(x.valuedAt)}</small></span><span><strong>{formatINR(x.valueMinor)}</strong><small className={g>=0?"positiveText":"negativeText"}>{g>=0?"+":""}{formatINR(g)}</small></span></button>})}</div></>:<EmptyState title="No holdings yet" body="Add manually tracked investments without connecting a broker." action={<Button onClick={()=>setAddOpen(true)}><Plus size={15}/> Add holding</Button>}/>}</div>
   <div className="surface allocationSurface"><div className="surfaceHead"><div><span className="sectionKicker">ALLOCATION</span><h2>By asset class</h2></div></div>{allocation.length?<AllocationChart items={allocation}/>:<EmptyState title="No allocation yet" body="Asset allocation appears after you add holdings."/>}</div>
  </div>
  <HoldingDialog open={addOpen} onOpenChange={setAddOpen} onSave={holding=>{commit({...s,holdings:[...h,holding]});setAddOpen(false)}}/>
  <ValuationDialog holding={edit} open={!!edit} onOpenChange={v=>{if(!v)setEdit(null)}} onSave={v=>{if(!edit)return;commit({...s,holdings:h.map(x=>x.id===edit.id?{...x,valueMinor:v,valuedAt:localDateKey()}:x)});setEdit(null)}}/>
 </>;
}

function HoldingDialog({open,onOpenChange,onSave}:{open:boolean;onOpenChange:(v:boolean)=>void;onSave:(h:Holding)=>void}){const[name,setName]=useState(""),[assetClass,setAssetClass]=useState("Mutual fund"),[cost,setCost]=useState(""),[value,setValue]=useState("");useEffect(()=>{if(open){setName("");setAssetClass("Mutual fund");setCost("");setValue("")}},[open]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><form onSubmit={e=>{e.preventDefault();const c=Math.round(Number(cost)*100),v=Math.round(Number(value||cost)*100);if(!name.trim()||c<=0||v<=0)return;onSave({id:crypto.randomUUID(),name:name.trim(),assetClass,quantity:1,costMinor:c,valueMinor:v,valuedAt:localDateKey()})}}><DialogHeader><DialogTitle>Add holding</DialogTitle><DialogDescription>Fintra tracks investments; it does not place trades.</DialogDescription></DialogHeader><div className="dialogFields"><label className="span2"><span>Holding name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Nifty 50 Index Fund"/></label><label className="span2"><span>Asset class</span><select value={assetClass} onChange={e=>setAssetClass(e.target.value)}><option>Mutual fund</option><option>ETF</option><option>Stock</option><option>Deposit</option><option>Bond</option><option>Gold</option><option>Other</option></select></label><label><span>Cost basis</span><MoneyInput value={cost} onChange={e=>setCost(e.target.value)} placeholder="0"/></label><label><span>Current value</span><MoneyInput value={value} onChange={e=>setValue(e.target.value)} placeholder="Same as cost"/></label></div><DialogFooter><Button type="button" variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button type="submit">Add holding</Button></DialogFooter></form></DialogContent></Dialog>}

function ValuationDialog({holding,open,onOpenChange,onSave}:{holding:Holding|null;open:boolean;onOpenChange:(v:boolean)=>void;onSave:(v:number)=>void}){const[value,setValue]=useState("");useEffect(()=>{if(open&&holding)setValue(String(holding.valueMinor/100))},[open,holding]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Update current value</DialogTitle><DialogDescription>{holding?.name} · Last valued {holding?formatShortDate(holding.valuedAt):""}.</DialogDescription></DialogHeader><label className="dialogLabel"><span>Current value</span><MoneyInput value={value} onChange={e=>setValue(e.target.value)} placeholder="0"/></label><DialogFooter><Button variant="secondary" onClick={()=>onOpenChange(false)}>Cancel</Button><Button onClick={()=>{const v=Math.round(Number(value)*100);if(v>0)onSave(v)}}>Update value</Button></DialogFooter></DialogContent></Dialog>}